release_name: csv-processor
namespace: csv-processor
image_repository: umar20/k8s-csv-processing-platform
image_tag: "0.1.0"
image_pull_policy: IfNotPresent
aws_profile: aws-personal
aws_region: eu-west-1
s3_bucket_name: ""
s3_upload_prefix: processed-csv
helm_chart_path: ../helm/csv-processor
